Nama=("Muhamad Iqbal Firmansyah Ramadhan")
Nim=("SI20230025")
Semester=int(2)
Hobi=("main game,traveling(sekitar rumah)")
Umur=int(21)
Alamat=("Leneng,Praya")
Lulusan=("SMAN 1 PRAYA TENGAH")
Jurusan=("SISTEM INFORMASI")

print("="*27)
print("===== BIODATA PRIBADI =====")
print("="*27)
print("selamat datang",Nama)
print("NIM :",Nim)
print("Jurusan :",Jurusan)
print("Semester :",Semester)
print("Hobi :",Hobi)
print("Umur :",Umur)
print("Alamat :",Alamat)
print("Lulusan Sekolah :",Lulusan)
print("="*27)